In [26]:
import pandas as pd

In [27]:
externals_df = pd.read_csv('data/external-forecasts-v900.csv')
externals_df

     TAZ     2020   2030   2040   2050   2060
0   3601    750.0    940   1140   1340   1530
1   3602   9570.0  10740  11900  13060  14230
2   3603   1480.0   1680   1880   2080   2280
3   3604  28390.0  33020  37650  42280  46920
4   3605   3840.0   4360   4880   5400   5920
5   3606  20210.0  23540  26870  30190  33520
6   3607   2090.0   2460   2830   3200   3570
7   3608   9200.0   9720  10240  10810  11380
8   3609  23820.0  29080  34350  39610  44780
9   3610    100.0    100    150    150    200
10  3611      NaN   5720   6920   7530   8200
11  3612  49550.0  50850  56670  63080  69940
12  3613    450.0    560    670    790    900
13  3614  58240.0  68330  78420  88500  98590
14  3615    460.0    520    580    640    700
15  3616    320.0    340    380    420    460
16  3617   1810.0   2090   2360   2650   2950
17  3618   1970.0   2410   2850   3290   3730
18  3619    400.0    450    500    550    600
19  3620  12110.0  14070  16020  18030  20040
20  3621    350.0    350    400    400    450
21  3622    100.0    150    150    200    200
22  3623   8220.0   8810   9400   9990  10580
23  3624   1870.0   2010   2150   2290   2430
24  3625    100.0    150    150    200    200
25  3626   3100.0   3560   4120   4680   5250
26  3627    350.0    350    400    400    450
27  3628  29000.0  34940  41380  47820  54260
28  3629   1690.0   2180   2670   3170   3660

In [28]:
externals_df = externals_df.melt(id_vars=['TAZ'], var_name="year", value_name="AADT")
externals_df['forecast'] = 'v900'
externals_df.rename(columns={'TAZ':'externalid'}, inplace=True)
externals_df

     externalid  year     AADT forecast
0          3601  2020    750.0     v900
1          3602  2020   9570.0     v900
2          3603  2020   1480.0     v900
3          3604  2020  28390.0     v900
4          3605  2020   3840.0     v900
..          ...   ...      ...      ...
140        3625  2060    200.0     v900
141        3626  2060   5250.0     v900
142        3627  2060    450.0     v900
143        3628  2060  54260.0     v900
144        3629  2060   3660.0     v900

[145 rows x 4 columns]

In [29]:
externals_df.to_csv("intermediate/previous-forecasts.csv", index=False)